### ISSUE TITLE
Glide dockings using local machine

### ISSUE THREAD

**Issue by Oulfin** [MolecularAI/DockStream#1]
Hi, I am trying to play with DockStream using Schrodinger. I am wondering if there is the possibility to use it in the local machine specifying $SCHRODINGER/glide instead of the tokens procedure.

**Comment by CMargreitter** [comment]
Hi Oulfin,

The usage of the "token guard" and the prefix are completely optional. You should be able to use something such as in [the Glide tutorial](https://github.com/MolecularAI/DockStreamCommunity/blob/master/notebooks/demo_Glide.ipynb), just remove the "prefix_execution" line.

In general, you have two options to steer how the backends are executed: Either by using "prefix_execution" (which is run directly before execution) or by specifying the binary path.

I haven't tried something like:
`...
"parameters": {
          "binary_location": "$SCHRODINGER",
          "parallelization": {
            "number_cores": 2
          },
          "glide_flags": {
            "-HOST": "localhost"
          },
...`

**Comment by Oulfin** [comment]
Hi,

Thanks, I am try to follow the Glide tutorial.

I have included different options in binary location, like opt/schrodinger2021-2/, opt/schrodinger2021-2/glide, $SCHRODINGER, $SCHRODINGER/glide

            **"binary_location": "/opt/schrodinger2021-2/",
            "parallelization": {                              # if present, the number of cores to be used
                                                            # can be specified
            "number_cores": 2
          },**

But all of them ended up with the same error:

**Traceback (most recent call last):
  File "~/Desktop/Play_AI/DockStream-master//docker.py", line 157, in <module>
    docker = Glide(**docking_run)
  File "~/Desktop/Play_AI/DockStream-master/dockstream/core/Schrodinger/Glide_docker.py", line 202, in __init__
    raise DockingRunFailed("Cannot initialize Glide docker, as Schrodinger backend is not available - abort.")
dockstream.utils.dockstream_exceptions.DockingRunFailed: Cannot initialize Glide docker, as Schrodinger backend is not available - abort.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/Desktop/Play_AI/DockStream-master//docker.py", line 187, in <module>
    raise DockingRunFailed() from e
dockstream.utils.dockstream_exceptions.DockingRunFailed**

Is it because I need to activate the license as Open Eye? If yes, how to activate it?

By the way it a really cool tool! Congrats for the work on this.

**Comment by CMargreitter** [comment]
Hi again,

Thanks, glad you find the package useful.

You have Glide installed on your machine, right?
So executing `$SCHRODINER/glide -h` properly returns the help message?

It is a proprietary solution and you need to obtain a license for it.

If you want to use `DockStream` with free software, you can use a combination of `RDkit embedding` + `AutoDockVina` or `rDock`.

**Comment by Oulfin** [comment]
Yes, I have my Glide installed and running ( I am using it every day with a valid license)
usage: glide_startup.py [options] <input_file>

positional arguments:
  input_file

optional arguments:
  -v, -version          Show the program's version and exit.
  -h, -help             Show this help message and exit.
  -k, -keywords         Print full list of available keywords.
  -docking-keywords     Print list of keywords available for docking jobs.
  -gridgen-keywords     Print list of keywords available for gridgen jobs.
  -allow_missing_inputs

The problem is if I need to tell some how DockStream that I have a valid license, or should it detect the license automatically?

Best,

**Comment by GuoJeff** [comment]
Hi Oulfin,

From your above comment, executing $SCHRODINGER correctly returns the Schrodinger installation directory. In the Glide tutorial, "module load schrodinger/2019-4 automatically sets all necessary environment variable paths. To specify the path to the Schrodinger installation directory manually, try replacing:

 "prefix_execution": "module load schrodinger/2019-4 --> **"prefix_execution": "export SCHRODINGER=$SCHRODINGER"**

I have tried this and it executes as intended.

In regards to the license detection, it should be automatic. If you execute "$SCHRODINGER/licadmin CHECK", it returns "License OK"?

**Comment by Oulfin** [comment]
Hi GuoJeff,

Thanks! 
This worked for me: **"export SCHRODINGER=/opt/schrodinger20xx"**

Best.
