### ISSUE TITLE
Check for glide backend looks for output from 'help' command, but help option not included

### ISSUE THREAD

**Issue by reskyner** [MolecularAI/DockStream#7]
When checking if the glide backend is available, the Schrodinger executor runs the glide command ``$SCHRODINGER/glide`` and checks that the string defined Schodinger_enums.py ``GLIDE_HELP_IDENTIFICATION_STRING`` is present in the output. This string is only returned when the help option is passed with the glide command, so the Schrodinger executor returns False when calling ``is_available()`` as the help option is not passed.

Tested with Schrodinger 2019-3 and 2021-2

https://github.com/MolecularAI/DockStream/blob/e33d181163be8461b2f7ef43436c14fc688af9e2/dockstream/utils/execute_external/Schrodinger.py#L40

https://github.com/MolecularAI/DockStream/blob/e33d181163be8461b2f7ef43436c14fc688af9e2/dockstream/utils/enums/Schrodinger_enums.py#L121

**Comment by GuoJeff** [comment]
Hi @reskyner,

I just wanted to check that your issue has been resolved? Thank you for your interest in DockStream.

**Comment by reskyner** [comment]
Hi Jeff,

Yes - solved and working great. I’d missed one of the execution prefix
parameters in the example I was running from dockstream community.

Thanks!
