### ISSUE TITLE
Question: Is it possible to feed an sdf file of prepared ligands straight into docking?

### ISSUE THREAD

**Issue by reskyner** [MolecularAI/DockStream#8]
I'm trying to work out whether it's possible to put an sdf file of prepared ligands straight into a Glide run? i.e. not specifying an input_pool to the docking_runs list? (especially when using docker.py)

**Comment by GuoJeff** [comment]
Hi @reskyner,

Yes, you can input prepared ligands in SDF format directly for docking. You can keep everything in the configuration JSON the same except for changing the following (**bolded**):

 "input": {
            **"input_path": <*path to .sdf ligands file*>"**,
            **"type": "sdf"**
          }

DockStream will recognize SDF format, skip ligand preparation, and use the coordinates in the .sdf file directly for docking.

**Comment by reskyner** [comment]
Perfect! Thank you so much for the quick reply.
